version: '3.6'

services:
  php:
    image: umanit/web:7.2
    restart: on-failure
    volumes:
      - .:/var/www/html:cached
      - ./build/php_log:/var/log/php:cached
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
